import java.io.Serializable;

/***
 * Student Name: Daniel Manzano Aguayo
 * Student ID: 1095549
 * 
 * Point.java
 * Class used to generate the points that composed the shapes objects,
 * and generated by the listener when the users clicks over the canvas
 * 
 */

public class Point implements Serializable {
    private int x;
    private int y;

    public Point(int x, int y) {
        this.x = x;
        this.y = y;
    }

    public static void switchPoints(Point p1, Point p2) {
        int tempX = p1.getX();
        int tempY = p1.getY();

        p1.setX(p2.getX());
        p1.setY(p2.getY());

        p2.setX(tempX);
        p2.setY(tempY);
    }

    public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }

    public int getY() {
        return y;
    }

    public void setY(int y) {
        this.y = y;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        Point other = (Point) obj;
        return this.x == other.x && this.y == other.y;
    }

    @Override
    public int hashCode() {
        // Simple hash code calculation using prime numbers
        int prime = 31;
        int result = 1;
        result = prime * result + x;
        result = prime * result + y;
        return result;
    }
}